### ISSUE TITLE
Support fields on associations

### ISSUE THREAD

**Issue by Stex** [makandra/minidusen#9]
Hey!

First of all, I really like the approach this gem takes, down to the filter definitions.

As far as I see, it's currently not possible to include columns on joined tables into the search, e.g.

```ruby
class User < ApplicationRecord
  has_many :pages
  # columns: :email
end

class Page
  belongs_to :user
  #columns: :name
end

# Not working since associations are not taken into account
Page.includes(:user).where_like([:name, {user: [:email]}], "my query")
```

If I'd like to display a table of pages including the email of the person administrating them, I wouldn't be able to filter it by both  the page name and email address. It always uses the table name belonging to the model I called `where_like`on.

Is this a planned feature?

**Comment by triskweline** [comment]
You can filter a joined table like so:

```
Page.includes(:user).where_like([:name, 'users.email', "my query")
```

It would be nice to support the syntax in your example though.

**Comment by Stex** [comment]
Sorry about this issue, I was simply blind  and missed the 

```ruby
unless column_name.include?('.')
```

condition inside `Util.qualify_column_name`. 

Might be worth adding this to the README though

**Comment by triskweline** [comment]
I added a section about this to the README.
